### ISSUE TITLE
Low resolution icon

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.geeqie.Geeqie#1]
The icon used for Geeqie Flatpak has low resolution/quality. Please, consider using a better one.

**Comment by Hofer-Julian** [comment]
As far as I know there is no better one, if you want to contribute https://github.com/BestImageViewer/geeqie/issues is the place to go.

**Comment by bilelmoussaoui** [comment]
There's an SVG icon in the repo https://github.com/BestImageViewer/geeqie/blob/master/src/icons/svg/gqview_icon.svg, it could be used here :)

**Comment by Hofer-Julian** [comment]
Nice catch @bilelmoussaoui
Didn't know about this.

Will look into it tomorrow!

**Comment by Hofer-Julian** [comment]
The next build will use the svg, thanks @bilelmoussaoui and @AsciiWolf for your input.
