### ISSUE TITLE
[Feature Request] Package a copy of the Breeze theme

### ISSUE THREAD

**Issue by ssokolow** [flathub/org.geeqie.Geeqie#14]
The decision to use GTK+2 (issue #4) combined with the lack of a Flatpak package for the GTK+2 version of KDE's default theme (Breeze) leaves Flatpak'd Geeqie looking deal-breakingly ugly on a KDE desktop.

Here's a screenshot comparing Flatpak'd Geeqie 1.7.2 (left) with the copy of Geeqie 1.5.1 from the *buntu APT repositories (right) that I've been sticking with as a result of that.

![Screenshot_20220325_045416](https://user-images.githubusercontent.com/46915/160089349-97fc9d21-0d52-4158-8fb2-453d15f25cfc.png)

Given that Breeze is KDE's equivalent to Adwaita, if you're going to build against GTK+2, could you please do one of the following?

1. Package up a GTK+2.x equivalent to however `org.gtk.Gtk3theme.Breeze` gets pulled in by GTK3 apps.
2. Bundle a copy of Breeze into the Geeqie Flatpak.

(If GNOME were still using Clearlooks, I'd suggest forcing that to be the fallback as a third option, but I'm not a big fan of the love for excessive padding, drop shadows, and needlessly redesigned context menus in Adwaita.)

**Comment by Hofer-Julian** [comment]
Geeqie uses GTK 3 nowadays
