### ISSUE TITLE
GTK3 Disabled?

### ISSUE THREAD

**Issue by yourealwaysbe** [flathub/org.geeqie.Geeqie#16]
I notice in b7ce1ded11c0aa35dc19dc63d0f34f74066b5fdd the GTK version was downgraded from 3 to 2. GTK3 would provide native Wayland support. Is there a particular reason it was removed?

**Comment by Hofer-Julian** [comment]
See https://github.com/flathub/org.geeqie.Geeqie/pull/4

**Comment by Hofer-Julian** [comment]
Feel free to update the manifest to gtk3 in a PR and test if the bug has been fixed :)

If it's fixed, I will merge it.

**Comment by yourealwaysbe** [comment]
Hah, thought you might say that :) I'll have a go once i learn how to do something more than just "flatpak install".

**Comment by paperdigits** [comment]
Clutter needs to be available inside the flatpak sandbox.

**Comment by Hofer-Julian** [comment]
@yourealwaysbe just open a PR with what you have and we can look there.

**Comment by yourealwaysbe** [comment]
Thanks, in the end i updated the shared modules and added clutter. PR made, though needs testing.
