### ISSUE TITLE
RDNS format

### ISSUE THREAD

**Issue by caclark** [flathub/org.geeqie.Geeqie#36]
Should the format be:
`org.Geeqie.geeqie`
rather than:
`org.geeqie.Geeqie`

Where `Geeqie` is the organisation, and `geeqie` is the executable name?

**Comment by paperdigits** [comment]
I believe so, this is how it is for darktable even though we expressly do not capitalize things.

**Comment by Hofer-Julian** [comment]
Thanks for opening the issue.

Looking here it is not obvious to me which one is preferred: https://docs.flatpak.org/en/latest/conventions.html

But even if it would be better, I wouldn't change it. The UX for changing app ids is terrible and you need a very good reason to do that.
